### ISSUE TITLE
A problem with the data encoding

### ISSUE THREAD

**Issue by lovepluskaka** [superoneio/eos_sql_db_plugin#6]
When I sync the data into the database，the memo in the field of data in the actions table which contains Chinese is Garbled.
Such as 
```
 data : {"to": "ggg111111111", "from": "iamthemangqi", "memo": "æµ‹è¯•", "quantity": "0.0001 EOS"}
```
It's not effect when I Convert it to UTF-8 format.

**Comment by lovepluskaka** [comment]
The transaction_id is "a7eca313bfc1e09348d52b3eb7aa58075a7b99c6dabf6f85586cd3eb8afb1a4a"

**Comment by firesWu** [comment]
what is  your database character ?
```
mysql> select * from actions where transaction_id="a7eca313bfc1e09348d52b3eb7aa58075a7b99c6dabf6f85586cd3eb8afb1a4a" \G
*************************** 1. row ***************************
             id: 5372379
        account: eosio.token
 transaction_id: a7eca313bfc1e09348d52b3eb7aa58075a7b99c6dabf6f85586cd3eb8afb1a4a
            seq: 0
         parent: 0
           name: transfer
     created_at: 2018-08-16 14:34:51
           data: {"to": "ggg111111111", "from": "iamthemangqi", "memo": "测试", "quantity": "0.0001 EOS"}
  authorization: [{"actor":"iamthemangqi","permission":"active"}]
          eosto: ggg111111111
        eosfrom: iamthemangqi
       receiver: 
          payer: 
     newaccount: 
sellram_account: 
1 row in set (0.01 sec)
```
